apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-client-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client-deployment
  labels:
    app: proxy-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      terminationGracePeriodSeconds: 1
      serviceAccountName: proxy-client-sa
      containers:
      - name: proxy-client
        image: docker.io/zicongmei/proxy-client
        command:
          - /app/client
        args:
          - http://echo-server-service
        resources:
          limits:
            cpu: "500m" # 500 millicores
            memory: "256Mi" # 256 mebibytes

