apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-server-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      serviceAccountName: echo-server-sa
      containers:
      - name: echo-server
        image: docker.io/zicongmei/echo-server
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m" # 500 millicores
            memory: "256Mi" # 256 mebibytes
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
