apiVersion: v1
kind: ServiceAccount
metadata:
  name: reply-node-name-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reply-node-name-deployment
  labels:
    app: reply-node-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reply-node-name
  template:
    metadata:
      labels:
        app: reply-node-name
    spec:
      serviceAccountName: reply-node-name-sa
      containers:
      - name: reply-node-name
        image: docker.io/zicongmei/reply-node-name
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m" # 500 millicores
            memory: "256Mi" # 256 mebibytes
        env:
        - name: NODE_NAME 
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: reply-node-name-service
spec:
  selector:
    app: reply-node-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
